#!/bin/bash
RFHSCR_PROJECT_PATH=/home/av/Documents/StudHub/Student-Raiting

RFHSCR_BE_PROCESS_NAME=student-rating-BE
RFHSCR_FE_PROCESS_NAME=student-rating-FE

RFHSCR_BE_BUILD_COOLDOWN=5
RFHSCR_FE_BUILD_COOLDOWN=0
