#!/bin/bash
RFHSCR_PROJECT_PATH=/home/av/Documents/StudHub/Raiting-Teams-Events2

RFHSCR_BE_PROCESS_NAME=rating-teams-BE
RFHSCR_FE_PROCESS_NAME=rating-teams-FE

RFHSCR_BE_BUILD_COOLDOWN=5
RFHSCR_FE_BUILD_COOLDOWN=0
